// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwMkPIiBf-Kqq_W5agrFmNavzbfhiqjHg',
    appId: '1:275002153704:web:55dbf1458641e1efc4c75d',
    messagingSenderId: '275002153704',
    projectId: 'grace-daily-6f14c',
    authDomain: 'grace-daily-6f14c.firebaseapp.com',
    storageBucket: 'grace-daily-6f14c.firebasestorage.app',
    measurementId: 'G-V3FVRCL1G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHifFLI1tilxP1n92V78aCDCSpoodEnUA',
    appId: '1:275002153704:android:618577f6b5d33169c4c75d',
    messagingSenderId: '275002153704',
    projectId: 'grace-daily-6f14c',
    storageBucket: 'grace-daily-6f14c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXluBgXWItxIPerJaG5huV-3ZdrpyrUDw',
    appId: '1:275002153704:ios:cce50c5ddd495326c4c75d',
    messagingSenderId: '275002153704',
    projectId: 'grace-daily-6f14c',
    storageBucket: 'grace-daily-6f14c.firebasestorage.app',
    iosBundleId: 'com.tumtu.graceDaily',
  );
}
